// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:axon_ivy/features/task/domain/entities/case/case.dart';
import 'package:axon_ivy/features/task/domain/entities/document/document.dart';
import 'package:axon_ivy/features/task/domain/entities/task/task.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CaseTaskAdapter());
    registerAdapter(DocumentAdapter());
    registerAdapter(TaskIvyAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CaseTaskAdapter());
    registerAdapter(DocumentAdapter());
    registerAdapter(TaskIvyAdapter());
  }
}
